FORMAT: 1A


# "Majestic Thai"

Simple API allowing consumers to view results of the menu and the order.

## Menu Collection [/menu]

### Menu [GET]

+ Response 200 (application/json)

           {
        
               [
                    {
                    "Name": "Jollof Rice",
                    "Price": 3000,
                    "Category": "Rice"
                  },
                  {
                    "Name": "Fried Rice",
                    "Price": 5000,
                    "Category": "Rice"
                    
                  },
                  {
                    "Name": "Yellow Rice",
                    "Price": 5500,
                    "Category": "Rice"

                  },
                  {
                    "Name": "Rice and Stew",
                    "Price": 4000,
                    "Category": "Rice"
                  }
                  
                ]
           }
        
## Individual Item [/menu/{id}]

+ Parameters

    + id (number) - ID of the specific menu as requested
    
### My Item [GET]

+ Response 200 (application/json)

               {
                    "Name": "Rice and Stew",
                    "Price": 4000,
                    "Category": "Rice"

                }

## Order Collection [/orders]

### Orders [GET]

+ Response 200 (application/json)

            {
    
                [
                    {
                        "username": "Absolutestunna",
                        "Name": "Jollof Rice",
                        "Price": 4900,
                        "Category": "Chicken"
                    },
                    {
                        "username": "Absolutestunna",
                        "Name": "Jollof Rice",
                        "Price": 4900,
                        "Category": "Chicken"
                    }
                ]
    
            }
        
## Individual Order [/order/{id}]

+ Parameters

    + id (number) - ID of the specific menu as requested
    
### My Order [GET]

+ Response 200 (application/json)

            {
                "username": "Absolutestunna",
                "Name": "Jollof Rice",
                "Price": 4900,
                "Category": "Chicken"
            }