FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# "MajesticThai"

Simple API allowing consumers to view results and vote in them.

## Menu Collection [/menu]

### List All Questions [GET]

+ Response 200 (application/json)

               [
                    {"Name": "Jollof Rice",
                    "Price": 3000,
                    "Category": "Rice"
                  },
                  {
                    "Name": "Fried Rice",
                    "Price": 5000,
                    "Category": "Rice"
                  },
                  {
                    "Name": "Yellow Rice",
                    "Price": 5500,
                    "Category": "Rice"
                  },
                  {
                    "Name": "Rice and Stew",
                    "Price": 4000,
                    "Category": "Rice"
                  },
                  {
                    "Name": "Chicken Stew",
                    "Price": 4900,
                    "Category": "Chicken"
                  },
                  {
                    "Name": "Chocolate Thunder",
                    "Price": 9000,
                    "Category": "Dessert"
                  }
                ]


### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }